<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Company></Company>
    <RepositoryUrl>https://github.com/ili/TinkofClientApi</RepositoryUrl>
    <VersionPrefix>0.5.0</VersionPrefix>
    <VersionSuffix>preview.1</VersionSuffix>
    <RepositoryType>Public</RepositoryType>
    <PackageReleaseNotes></PackageReleaseNotes>
    <NeutralLanguage></NeutralLanguage>
    <Authors>RomeProduction, ili</Authors>
    <Product>Tinkoff Payment API Client</Product>
    <Description>Unofficial .Net Tinkoff Payment API implementation</Description>
    <PackageProjectUrl>https://github.com/ili/TinkofClientApi</PackageProjectUrl>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <NoWarn>1701;1702;1591</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>Latest</LangVersion>
    <Nullable>enable</Nullable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageId>TinkoffPaymentClientApi.Unofficial</PackageId>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <None Include="../README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.ru.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  
</Project>
